name: "🐛 バグ報告"
description: 不具合を報告するフォーム
title: "[Bug] <タイトルを入力>"
labels: ["bug", "help wanted"]
assignees: ["akiomatic"]

body:
  - type: markdown
    attributes:
      value: |
        ## バグ概要
        再現手順と期待動作をできるだけ詳細に記載してください。

  - type: input
    id: summary
    attributes:
      label: 概要
      placeholder: 例）チェックボックスがスマホでタップできない
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      placeholder: 正常にチェックが入る
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
      placeholder: チェックが入らない
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: 環境
      placeholder: |
        - OS: iOS 17.4
        - Browser: Safari
        - App Version: v0.1.2
    validations:
      required: false

  - type: input
    id: related
    attributes:
      label: 関連 Issue / PR
      placeholder: 例）#45
    validations:
      required: false