blank_issues_enabled: true
contact_links: []

issue_templates:
  - name: Task
    description: 開発タスクを登録するフォーム
    file: task.yml
  - name: Bug Report
    description: バグを報告するフォーム
    file: bug-report.yml