blank_issues_enabled: true
contact_links: []

issue_templates:
  - name: Task
    description: 開発タスクを登録するフォーム
    file: 1-task.yml
  - name: Bug Report
    description: バグを報告するフォーム
    file: 2-bug-report.yml